name: optimization
version: 0.0.0
homepage: https://github.com/morloc-lib/optimization
synopsis: Numeric optimization functions
description: See README
category: math
license: MIT
author: "Zebulun Arendsee"
maintainer: "zbwrnz@gmail.com"
github: https://github.com/morloc-lib/optimization
bug-reports: https://github.com/morloc-lib/optimization
gcc-flags: "-Wall -lm -lgs -lgslcblas"
